apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.name" . }}-auth
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
