apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.name" . }}-initdb
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  01-create-databases.sql: |
    {{- range .Values.databases }}
    CREATE DATABASE {{ . }};
    GRANT ALL PRIVILEGES ON DATABASE {{ . }} TO {{ $.Values.auth.username }};
    {{- end }}
