apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.name" . }}-auth
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d" .Values.auth.username .Values.auth.password (include "postgres.name" .) (int .Values.service.port) | quote }}
