# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bulkhead/retrieval/v1/retrieval.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bulkhead/retrieval/v1/retrieval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%bulkhead/retrieval/v1/retrieval.proto\x12\x15\x62ulkhead.retrieval.v1\"C\n\x0fRetrieveRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12\x12\n\ncorpus_ref\x18\x03 \x01(\t\"\x8a\x01\n\x05\x43hunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\r\n\x05score\x18\x05 \x01(\x02\x12\x15\n\rcorpus_commit\x18\x06 \x01(\t\x12\x18\n\x10ingested_at_unix\x18\x07 \x01(\x03\"@\n\x10RetrieveResponse\x12,\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x1c.bulkhead.retrieval.v1.Chunk\"\x10\n\x0eHealthzRequest\"&\n\x0fHealthzResponse\x12\x13\n\x0b\x64\x61tabase_ok\x18\x01 \x01(\x08\x32\xc9\x01\n\x10RetrievalService\x12[\n\x08Retrieve\x12&.bulkhead.retrieval.v1.RetrieveRequest\x1a\'.bulkhead.retrieval.v1.RetrieveResponse\x12X\n\x07Healthz\x12%.bulkhead.retrieval.v1.HealthzRequest\x1a&.bulkhead.retrieval.v1.HealthzResponseBcZagithub.com/devanshshah-tech/BulkHead/apps/retrieval-service/gen/bulkhead/retrieval/v1;retrievalv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bulkhead.retrieval.v1.retrieval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zagithub.com/devanshshah-tech/BulkHead/apps/retrieval-service/gen/bulkhead/retrieval/v1;retrievalv1'
  _globals['_RETRIEVEREQUEST']._serialized_start=64
  _globals['_RETRIEVEREQUEST']._serialized_end=131
  _globals['_CHUNK']._serialized_start=134
  _globals['_CHUNK']._serialized_end=272
  _globals['_RETRIEVERESPONSE']._serialized_start=274
  _globals['_RETRIEVERESPONSE']._serialized_end=338
  _globals['_HEALTHZREQUEST']._serialized_start=340
  _globals['_HEALTHZREQUEST']._serialized_end=356
  _globals['_HEALTHZRESPONSE']._serialized_start=358
  _globals['_HEALTHZRESPONSE']._serialized_end=396
  _globals['_RETRIEVALSERVICE']._serialized_start=399
  _globals['_RETRIEVALSERVICE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
