apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lakefs.name" . }}-data
  labels:
    {{- include "lakefs.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.storage.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
