apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakefs.name" . }}-auth
  labels:
    {{- include "lakefs.labels" . | nindent 4 }}
type: Opaque
stringData:
  LAKEFS_AUTH_ENCRYPT_SECRET_KEY: {{ .Values.encryptSecretKey | quote }}
